services:
  backend:
    build:
      context: "."
      dockerfile: "./docker/backend.dockerfile"
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./log:/app/log
      - ./tmp:/app/tmp
    ports:
      - "9220:9220"

  frontend:
    build:
      context: "."
      dockerfile: "./docker/frontend.dockerfile"
    ports:
      - "3000:3000"
    depends_on:
      - backend
