---
- name: Provision MicoroArray Local Development Environment
  hosts: all
  become: yes
  become_method: sudo
  environment:
    PATH: '{{ ansible_env.PATH }}:/usr/local/bin'
  vars:
    - app: microArray
    - config_folder: '{{ apps_directory }}/apps/{{ app }}/config'
  tasks:
    - name: install system packages
      include_role:
        name: install-system-packages

    - name: common server settings
      include_role:
        name: common-server-setup

    - name: Install system level packages
      yum:
        name:
          - xorg-x11-server-Xvfb
          - xorg-x11-font-utils
          - wkhtmltopdf
          - pandoc
          - glx-utils
          - libxml2
          - libxml2-devel
          - mesa-libGL
          - mesa-libGL-devel
          - mesa-libGLU
          - mesa-libGLU-devel
          - freetype-devel
        state: present
        update_cache: yes
        disable_gpg_check: yes

    - name: Setup xvfb service
      include_role:
        name: configure-xvfb-service

    - name: Install R packages
      include_role:
        name: install-R-packages-standard
      vars:
        packages:
          - name: mvtnorm
            version: '1.0-8'
          - name: jsonlite
          - name: caTools
            version: '1.17.1.4'
          - name: gplots
          - name: TSP
            version: '1.1-8'
          - name: httpuv
            version: '1.5.4'
          - name: shiny
            version: '1.3.2'
          - name: rgl
          - name: rglwidget
          - name: DT
          - name: getopt
          - name: knitr
          - name: reshape
          - name: RColorBrewer
          - name: calibrate
          - name: rmarkdown
          - name: ggplot2
          - name: ggfortify
          - name: shinyRGL
          - name: plotly
            version: '4.9.2.1'
          - name: htmltools
          - name: heatmaply
          - name: pheatmap
          - name: viridis
          - name: dendsort
          - name: amap
          - name: RCurl
          - name: ff
            version: '2.2-14'

    - name: Install biocLite R packages
      include_role:
        name: install-R-packages-biocLite
      vars:
        - packages:
            - mixOmics
            - GEOquery
            - pd.clariom.s.rat
            - clariomsrattranscriptcluster.db
            - pd.mogene.2.0.st
            - mogene20sttranscriptcluster.db
            - pd.hg.u133.plus.2
            - hgu133plus2.db
            - pd.hugene.2.0.st
            - hugene20sttranscriptcluster.db
            - pd.clariom.s.human.ht
            - clariomshumanhttranscriptcluster.db
            - pd.clariom.s.human
            - clariomshumantranscriptcluster.db
            - pd.clariom.s.mouse.ht
            - clariomsmousehttranscriptcluster.db
            - pd.clariom.s.mouse
            - clariomsmousetranscriptcluster.db
            - pd.mouse430.2
            - mouse4302.db
            - pd.hg.u133a
            - hgu133a.db
            - pd.hugene.1.0.st.v1
            - hugene10sttranscriptcluster.db
            - pd.mogene.1.0.st.v1
            - mogene10sttranscriptcluster.db
            - pd.hg.u133a.2
            - hgu133a2.db
            - pd.huex.1.0.st.v2
            - huex10sttranscriptcluster.db
            - pd.hg.u219
            - hgu219.db
            - pd.mg.u74av2
            - mgu74av2.db
            - pd.mouse430a.2
            - mouse430a2.db
            - pd.moe430a
            - moe430a.db
            - pd.hg.u95av2
            - hgu95av2.db
            - pd.hta.2.0
            - hta20transcriptcluster.db
            - pd.moex.1.0.st.v1
            - moex10sttranscriptcluster.db
            - pd.hg.u133b
            - hgu133b.db
            - pd.hugene.1.1.st.v1
            - hugene11sttranscriptcluster.db
            - pd.mogene.1.1.st.v1
            - mogene11sttranscriptcluster.db
            - limma
            - oligo
            - geneplotter
            - multtest
            - annotate
            - Biobase
            - GSVA
            - GSEABase
            - pd.hugene.2.1.st
            - hugene21sttranscriptcluster.db
            - sva
            - pd.ht.hg.u133a
            - hthgu133a.db
            - pd.clariom.d.human
            - clariomdhumantranscriptcluster.db

    - name: Install npm packages
      npm:
        name: '{{ item }}'
        global: yes
        state: present
      with_items:
        - forever
        - yarn
        - xvfb
        - webpack-cli

    - name: Create config folder for {{ app }}
      file:
        dest: '{{ config_folder }}'
        state: directory
        owner: '{{ ncianalysis_user }}'
        group: apache
